import type { Metadata } from "next";
import "./globals.css";
import { open_sans, playfair } from "@/lib/ui/font";
import CryptoPrice from "@/components/LandingPage/CryptoPrice";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${playfair.variable}`}>
        <main className=" m-0 p-0 w-full h-screen relative h-[calc(100vh - 250px)] bg-green">
          {/* <CryptoPrice /> */}

          {children}
        </main>
      </body>
    </html>
  );
}
