import type { Metadata } from "next";
import "./globals.css";
import { open_sans, playfair } from "@/components/ui/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${open_sans.variable} ${playfair.variable} scroll-smooth`}
      >
        {children}
      </body>
    </html>
  );
}
